spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ewangclarkson/spring-cloud-microservices/tree/main/config-properties
server:
  port: 8088


